# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('blog', '0009_auto_20171109_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='date_published',
            field=models.DateField(blank=True, null=True, verbose_name='Date article published'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Landscape mode only; horizontal width between 1000px and 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Text to describe the page'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
