# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 05:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20171109_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='date_published',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 9, 5, 34, 17, 170476, tzinfo=utc), null=True, verbose_name='Date article published'),
        ),
    ]
