# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20171109_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='date_published',
            field=models.DateField(blank=True, null=True, verbose_name='Date article published'),
        ),
    ]
